// Re-export everything from db.ts
export {
  getDb,
  connectDb,
  disconnectDb,
  createUser,
  getUserByTelegramId,
  getUserById,
  getUserBySubaccount,
  updateUserScopedKey,
  updateUserDefaults,
  updateUserSettings,
  createPosition,
  getOpenPositions,
  getPositionById,
  updatePosition,
  createFill,
  getFillsByPosition,
  createTrigger,
  getActiveTriggers,
  getTriggersByPosition,
  markTriggerFired,
  getTokenCache,
  upsertTokenCache,
  recordFee,
  generateReferralCode,
  getUserByReferralCode,
  createReferral,
  activateReferral,
  addReferralReward,
  getReferralsByReferrer,
  getReferralByReferredUser,
  getTotalReferralEarnings,
} from './db.js';

export type {
  UserRecord,
  PositionRecord,
  FillRecord,
  TriggerRecord,
  TokenCacheRecord,
  ReferralRecord,
  CreateUserParams,
  CreatePositionParams,
  CreateFillParams,
  CreateTriggerParams,
  UpdatePositionParams,
  UpdateUserSettingsParams,
} from './db.js';